const types = {
  GET_PHOTO_REQUEST: "GET_PHOTO_REQUEST",
  GET_PHOTO_SUCCESS: "GET_PHOTO_SUCCESS",
  GET_PHOTO_FAILED: "GET_PHOTO_FAILED",

  DELETE_PHOTO_REQUEST: "DELETE_PHOTO_REQUEST",
  EDIT_PHOTO_REQUEST: "EDIT_PHOTO_REQUEST",
  ADD_PHOTO_REQUEST: "ADD_PHOTO_REQUEST",
};

export default types;
